# https://github.com/FiloSottile/mkcert

version: "3.7"
services:
    app:
        build:
            args:
                user: omarceleza
                uid: 1000
            context: ./.docker/php/
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/
        networks:
            - ${DOCKER_NETWORK_NAME}
        depends_on:
            - db

    db:
        build:
            args:
                user: ${DOCKER_PERMISSION_USER}
                uid: ${DOCKER_PERMISSION_UID}
            context: .docker/postgres/
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: ${DOCKER_NETWORK_NAME}
            TZ: "America/Sao_Paulo"
        networks:
            - ${DOCKER_NETWORK_NAME}
        ports:
            - "5432:5432"
        volumes:
            - "pg_data:/var/lib/postgresql/data"
            - "./storage/database_backups:/backups"
            # - ./.docker/postgres/init/init.sql:/docker-entrypoint-initdb.d/db.sql
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        # container_name: nginx
        tty: true
        restart: unless-stopped
        ports:
            - 8086:80
        volumes:
            - ./.docker/nginx/conf.dev.d:/etc/nginx/conf.d
            - ./.docker/nginx/logs:/var/log/nginx
            - ./:/var/www/
        networks:
            - ${DOCKER_NETWORK_NAME}

    node:
        build:
            context: ./.docker/node
            args:
                user: omarceleza
                uid: 1000
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            # - ${HOME}/.npm:${HOME}/.npm
        command: npm run dev
        ports:
            - 5173:5173
        depends_on:
            - app

    npm:
        image: node:14-slim
        working_dir: /var/www/
        entrypoint: ["npm"]
        profiles:
            - donotstart
        volumes:
            - "./:/var/www/"

    supervisor:
        build:
            args:
                user: omarceleza
                uid: 1000
            context: .docker/supervisor
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/var/www/
        networks:
            - ${DOCKER_NETWORK_NAME}
        depends_on:
            - app

networks:
    investCubo:
        driver: bridge

volumes:
    pg_data:
        # driver_opts:
        #     type: tmpfs
        #     device: tmpfs
